### ISSUE TITLE
After executing "Show All Commands" the arrow keys can push the result targeting out of bounds

### ISSUE THREAD

**Issue by Olian04** [cliffordfajardo/cato#10]
After executing "Show All Commands" the arrow keys can push the result targeting out of bounds.
Ex: 
1. Search for: `Show All Commands`, and execute the command.
2. Press the `up` key. The targeting has now been lost. 

__Versions:__
Cato: 1.1.2
Chrome: 60.0.3112.113
OS: Ubuntu 17.04

**Comment by cliffordfajardo** [comment]
Fixed, will get it out in the next release today. Thanks!

Fixed in this [commit](https://github.com/cliffordfajardo/cato/commit/675e1068c1bf172f48a8aa6631688df8ab6a6a01)

**Comment by Olian04** [comment]
@cliffordfajardo Still kind of broken.
Replicate:
1. Search for `Show All Commands` and execute the command.
2. Press the `up` key. (In principal you only need to press it once, but in order to easier see the problem, press it at least 10 times.)
3. Press the `down` key. The targeting should now have jumped all the way down to the last visible result.
