### ISSUE TITLE
Reload tab command(s) description

### ISSUE THREAD

**Issue by round** [cliffordfajardo/cato#4]
The command descriptions for `Reload Tab` and `Reload All Tabs` appear to be identical.

![image](https://user-images.githubusercontent.com/2340336/30787167-fc99526e-a150-11e7-9157-31eb5066d7bb.png)

Caused me to double-take at first :)

**Comment by cliffordfajardo** [comment]
Thanks for reporting! Will fix this in the next release 🚀

**Comment by cliffordfajardo** [comment]
This [commit](https://github.com/cliffordfajardo/cato/commit/d80f3cf84cdeca97082f353125aa4e511c1c6512) fixes the issue
