### ISSUE TITLE
Pressing the up button resets the caret position to the beginning of the search string

### ISSUE THREAD

**Issue by Olian04** [cliffordfajardo/cato#5]
Pressing the up key moves the caret to the beginning of the search string, but pressing the down key moves the caret to the end of the search string.
__Ex:__ 
1. Search for `i`
2. Press the `Up` key on the keyboard. The caret should now have moved to the beginning of the search string.
3. Press the 'Down' key on the keyboard. The caret should now have moved to the end of the search string.

__Versions:__ 
Cato: 1.1.2
Chrome: 60.0.3112.113
OS: Ubuntu 17.04

**Comment by cliffordfajardo** [comment]
Fixed in this [commit](https://github.com/cliffordfajardo/cato/commit/f698e2c8f259fb6e025bcff838d093095ec2398d). 

Let me know if this doesn't work in the newer version of cato of [1.1.3](https://chrome.google.com/webstore/detail/cato/icphdcfpompgbdikholnedfeidemgobg)

**Comment by Olian04** [comment]
@cliffordfajardo It's still broken in 1.1.3
