### ISSUE TITLE
Add documentation for how to contribute with new commands

### ISSUE THREAD

**Issue by Olian04** [cliffordfajardo/cato#7]
I decided I would look into contributing to the project, so i started looking through the source code, that's when i saw your `plugins` folder, and it looks as if every command available through the command pallet has its own folder? Whether or not this is everything needed to add a new command, I think allot of people would appreciate some documentation on how you would contribute to the project in the way of adding new commands.

**Comment by cliffordfajardo** [comment]
@Olian04 - 

> "it looks as if every command available through the command pallet has its own folder?"

Yep - that's how it works at the moment.

I'll create a new contributing doc and link it in the README thanks!

**Comment by cliffordfajardo** [comment]
Added in this [commit](https://github.com/cliffordfajardo/cato/commit/814a165a5f5c07194873308437d9dac5317a6aa6)
