### ISSUE TITLE
Command pallet doesn't close after `Copy Url` command has been executed

### ISSUE THREAD

**Issue by Olian04** [cliffordfajardo/cato#8]
__Versions:__
Cato: 1.1.2
Chrome: 60.0.3112.113
OS: Ubuntu 17.04

**Comment by Olian04** [comment]
Temporary fix as part of https://github.com/cliffordfajardo/cato/pull/9

**Comment by Olian04** [comment]
@cliffordfajardo my bad, i wrote "clone" when it should have been "close". Wops

**Comment by cliffordfajardo** [comment]
Fixed in this [commit](https://github.com/cliffordfajardo/cato/commit/590e3631ad5aca2b5f36bba048fe5bb838ffa376)
